export const GITHUB_PROFILE = 'GITHUB_PROFILE';
export const GITHUB_PROFILE_URL = 'https://api.github.com/users/aarora11';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const GITHUB_REPOSITORIES = 'GITHUB_REPOSITORIES';
export const GITHUB_REPOSITORY_DETAILS = 'GIHUB_REPOSITORY_DETAILS';
export const GITHUB_COMMIT_PER_USER = 'GITHUB_COMMIT_PER_USER';
export const SELECTED_REPOSITORY = 'SELECTED_REPOSITORY'

